name: 'Notify Workflow'
description: 'Send workflow status over a Telegram bot and Firebase'
author: 'yakuhzi'
inputs:
  job-status:
    description: 'Job status'
    required: true
  bot-token:
    description: 'Telegram bot token'
    required: true
  chat-id:
    description: 'Chat to send the status'
    required: true
runs:
  using: 'node20'
  main: 'dist/main.js'
branding:
  color: 'blue'
  icon: 'send'
